[github_app]
pr_commands = ["/describe", "/review --pr_reviewer.num_code_suggestions=0"]
handle_push_trigger = true
push_commands = [
    "/describe",
    "/review",
]

[pr_description]
generate_ai_title=false
publish_description_as_comment = true
add_original_user_description = false
use_description_markers = true

[config]
# auto approval 💎
enable_auto_approval=true # Set to true to enable auto-approval of PRs under certain conditions
auto_approve_for_low_review_effort=2 # -1 to disable, [1-5] to set the threshold for auto-approval

[pr_code_suggestions]
wiki_page_accepted_suggestions = true
