[pr_reviewer]
num_code_suggestions = 4  # Set this to the number of code suggestions you want (default is 0)
inline_code_comments = false  # Optional: set to true if you want suggestions as inline comments
